<?php

// Include DatabaseHelper.php file
require_once('DatabaseHelper.php');

// Instantiate DatabaseHelper class
$database = new DatabaseHelper();

// Get parameter 'person_id', 'surname' and 'name' from GET Request
// Btw. you can see the parameters in the URL if they are set
$person_id = '';
if (isset($_GET['person_id'])) {
    $person_id = $_GET['person_id'];
}

$surname = '';
if (isset($_GET['surname'])) {
    $surname = $_GET['surname'];
}

$name = '';
if (isset($_GET['name'])) {
    $name = $_GET['name'];
}

//Fetch data from database
$person_array = $database->selectAllPersons($person_id, $surname, $name);
?>

<html>
<head>
    <title>DBS Tutorial</title>
</head>

<body>
<br>
<h1>My First PHP Project</h1>

<!-- Add Person -->
<h2>Add Person: </h2>
<form method="post" action="addPerson.php">
    <!-- ID is not needed, because its autogenerated by the database -->

    <!-- Name textbox -->
    <div>
        <label for="new_name">Name:</label>
        <input id="new_name" name="name" type="text" maxlength="20">
    </div>
    <br>

    <!-- Surname textbox -->
    <div>
        <label for="new_surname">Surname:</label>
        <input id="new_surname" name="surname" type="text" maxlength="20">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Add Person
        </button>
    </div>
</form>
<br>
<hr>

<!-- Delete Person -->
<h2>Delete Person: </h2>
<form method="post" action="delPerson.php">
    <!-- ID textbox -->
    <div>
        <label for="del_name">ID:</label>
        <input id="del_name" name="id" type="number" min="0">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Delete Person
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search form -->
<h2>Person Search:</h2>
<form method="get">
    <!-- ID textbox:-->
    <div>
        <label for="person_id">ID:</label>
        <input id="person_id" name="person_id" type="number" value='<?php echo $person_id; ?>' min="0">
    </div>
    <br>

    <!-- Name textbox:-->
    <div>
        <label for="name">Name:</label>
        <input id="name" name="name" type="text" class="form-control input-md" value='<?php echo $name; ?>'
               maxlength="20">
    </div>
    <br>

    <!-- Surname textbox:-->
    <div>
        <label for="surname">Surname:</label>
        <input id="surname" name="surname" type="text"
               value='<?php echo $surname; ?>' maxlength="20">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button id='submit' type='submit'>
            Search
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search result -->
<h2>Person Search Result:</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Surname</th>
    </tr>
    <?php foreach ($person_array as $person) : ?>
        <tr>
            <td><?php echo $person['PERSON_ID']; ?>  </td>
            <td><?php echo $person['NAME']; ?>  </td>
            <td><?php echo $person['SURNAME']; ?>  </td>
        </tr>
    <?php endforeach; ?>
</table>

</body>
</html>